#!/bin/bash
set -e
set -u
set -o pipefail

printf "\n\n\n"
python -c "import main; import json; print main.initiate_restore(json.loads(\"\"\"$1\"\"\"),'$2','$3').text.encode('utf-8').strip()" 
printf "\n\n\n"